"""Tests for FLAC PTS remux service."""

import shutil
import subprocess
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, patch

import pytest

from app.services.flac_remux import needs_remux

# Skip all tests if ffmpeg/ffprobe not available
pytestmark = pytest.mark.skipif(
    shutil.which("ffmpeg") is None or shutil.which("ffprobe") is None,
    reason="ffmpeg/ffprobe not available",
)


def _generate_flac(path: Path) -> None:
    """Generate a minimal FLAC file using ffmpeg (sine wave, 0.1s)."""
    subprocess.run(
        [
            "ffmpeg", "-y",
            "-f", "lavfi", "-i", "sine=frequency=440:duration=0.1",
            "-c:a", "flac",
            str(path),
        ],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        check=True,
    )
    assert path.exists() and path.stat().st_size > 0


class TestNeedsRemux:
    """Tests for needs_remux() PTS detection."""

    @pytest.mark.asyncio
    async def test_well_formed_flac_does_not_need_remux(self):
        """A FLAC generated by ffmpeg should have proper PTS."""
        with tempfile.TemporaryDirectory() as tmpdir:
            flac = Path(tmpdir) / "good.flac"
            _generate_flac(flac)
            assert await needs_remux(flac) is False

    @pytest.mark.asyncio
    async def test_returns_true_when_pts_is_na(self):
        """Should detect missing PTS from ffprobe output."""
        mock_proc = AsyncMock()
        mock_proc.communicate.return_value = (b"N/A\n", b"")
        mock_proc.kill = AsyncMock()

        with patch("app.services.flac_remux.asyncio.create_subprocess_exec", return_value=mock_proc):
            assert await needs_remux(Path("/fake/file.flac")) is True

    @pytest.mark.asyncio
    async def test_returns_true_when_output_empty(self):
        """Should treat empty ffprobe output as missing PTS."""
        mock_proc = AsyncMock()
        mock_proc.communicate.return_value = (b"", b"")
        mock_proc.kill = AsyncMock()

        with patch("app.services.flac_remux.asyncio.create_subprocess_exec", return_value=mock_proc):
            assert await needs_remux(Path("/fake/file.flac")) is True

    @pytest.mark.asyncio
    async def test_returns_false_when_pts_is_numeric(self):
        """Should recognize valid numeric PTS."""
        mock_proc = AsyncMock()
        mock_proc.communicate.return_value = (b"0\n", b"")
        mock_proc.kill = AsyncMock()

        with patch("app.services.flac_remux.asyncio.create_subprocess_exec", return_value=mock_proc):
            assert await needs_remux(Path("/fake/file.flac")) is False

    @pytest.mark.asyncio
    async def test_returns_false_on_timeout(self):
        """Should not request remux if ffprobe times out."""
        mock_proc = AsyncMock()
        mock_proc.communicate.side_effect = TimeoutError()
        mock_proc.kill = AsyncMock()
        mock_proc.wait = AsyncMock()

        with patch("app.services.flac_remux.asyncio.create_subprocess_exec", return_value=mock_proc):
            assert await needs_remux(Path("/fake/file.flac")) is False


