#!/usr/bin/env bash
set -euo pipefail

# analyze-demo-library.sh — Run a full local analysis pass on ./demo-library/
# so tracks/track_analysis rows (with CLAP embeddings) exist in a throwaway
# Postgres that seed-demo-library.sh can then dump into Neon.
#
# Does NOT require torch or Python on your Mac — uses the published
# ghcr.io/seethroughlab/familiar image which already has analysis + CLAP.
#
# Usage:
#   ./scripts/analyze-demo-library.sh            # up + scan + wait + print URL
#   ./scripts/analyze-demo-library.sh status     # poll sync status
#   ./scripts/analyze-demo-library.sh dump-url   # just print the DEMO_LOCAL_DB URL
#   ./scripts/analyze-demo-library.sh down       # stop + delete the throwaway stack
#
# Leaves the Postgres running on localhost:${DEMO_ANALYSIS_DB_PORT:-54932} so
# seed-demo-library.sh can pg_dump it. Run `… down` to clean up when you're done.

DEMO_LIBRARY_PATH="${DEMO_LIBRARY_PATH:-./demo-library}"
DEMO_ANALYSIS_DIR="${DEMO_ANALYSIS_DIR:-./.demo-analysis}"
DEMO_ANALYSIS_DB_PORT="${DEMO_ANALYSIS_DB_PORT:-54932}"
DEMO_ANALYSIS_API_PORT="${DEMO_ANALYSIS_API_PORT:-54980}"
# The published ghcr image is amd64-only, so on Apple Silicon we build
# natively from the repo's Dockerfile by default. Override with
# FAMILIAR_IMAGE=… if you already have an arm64 image locally.
IMAGE="${FAMILIAR_IMAGE:-}"

DEMO_LOCAL_DB="postgresql://familiar:familiar@localhost:${DEMO_ANALYSIS_DB_PORT}/familiar"

command -v docker >/dev/null || { echo "docker required" >&2; exit 1; }
command -v curl   >/dev/null || { echo "curl required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 required (for JSON parsing)" >&2; exit 1; }

COMPOSE_FILE="$DEMO_ANALYSIS_DIR/docker-compose.yml"
mkdir -p "$DEMO_ANALYSIS_DIR"

# Always (re)write the compose file so it reflects current env vars.
# Absolute path needed because docker compose resolves bind mounts relative
# to the compose file.
ABS_LIBRARY_PATH=$(cd "$DEMO_LIBRARY_PATH" 2>/dev/null && pwd || echo "")
REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)

write_compose() {
    # If an explicit image is set, use it; otherwise build from the repo
    # Dockerfile (needed for arm64 Macs since the published image is amd64).
    local api_spec
    if [ -n "$IMAGE" ]; then
        api_spec="    image: ${IMAGE}"
    else
        api_spec="    build:
      context: ${REPO_ROOT}
      dockerfile: docker/Dockerfile
    image: familiar-local:analysis"
    fi

    cat > "$COMPOSE_FILE" <<EOF
# Auto-generated by analyze-demo-library.sh — do not edit.
name: familiar-demo-analysis

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: familiar-demo-analysis-postgres
    environment:
      POSTGRES_USER: familiar
      POSTGRES_PASSWORD: familiar
      POSTGRES_DB: familiar
    ports:
      - "${DEMO_ANALYSIS_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U familiar"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: familiar-demo-analysis-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
${api_spec}
    container_name: familiar-demo-analysis-api
    ports:
      - "${DEMO_ANALYSIS_API_PORT}:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://familiar:familiar@postgres:5432/familiar
      REDIS_URL: redis://redis:6379/0
      MUSIC_LIBRARY_PATH: /music
    volumes:
      - ${ABS_LIBRARY_PATH}:/music:ro
      - app_data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 6G

volumes:
  pgdata:
  app_data:
EOF
}

# ── Subcommand handling ──────────────────────────────────────────────────────

cmd="${1:-up}"

case "$cmd" in
    dump-url)
        echo "$DEMO_LOCAL_DB"
        exit 0
        ;;
    status)
        curl -fsS "http://localhost:${DEMO_ANALYSIS_API_PORT}/api/v1/library/sync/status" \
            | python3 -m json.tool
        exit 0
        ;;
    down)
        if [ -f "$COMPOSE_FILE" ]; then
            docker compose -f "$COMPOSE_FILE" down -v
        fi
        rm -rf "$DEMO_ANALYSIS_DIR"
        echo "✓ Analysis stack torn down and state cleared."
        exit 0
        ;;
    up|"")
        : # fall through
        ;;
    *)
        echo "Unknown subcommand: $cmd" >&2
        echo "Use: up | status | dump-url | down" >&2
        exit 1
        ;;
esac

# ── up (default) ─────────────────────────────────────────────────────────────

[ -n "$ABS_LIBRARY_PATH" ] || { echo "No such dir: $DEMO_LIBRARY_PATH" >&2; exit 1; }
mp3_count=$(find "$ABS_LIBRARY_PATH" -maxdepth 1 -name '*.mp3' | wc -l | tr -d ' ')
[ "$mp3_count" -gt 0 ] || {
    echo "No MP3s in $DEMO_LIBRARY_PATH. Run scripts/fetch-demo-library.sh first." >&2
    exit 1
}

echo "→ Writing throwaway docker-compose to $COMPOSE_FILE"
write_compose

echo "→ Starting Postgres + Redis + API (image: $IMAGE)…"
docker compose -f "$COMPOSE_FILE" up -d

API_BASE="http://localhost:${DEMO_ANALYSIS_API_PORT}"

echo -n "→ Waiting for API health"
for _ in $(seq 1 60); do
    if curl -fsS "$API_BASE/api/v1/health" >/dev/null 2>&1; then
        echo " — ready."
        break
    fi
    echo -n "."
    sleep 2
done
if ! curl -fsS "$API_BASE/api/v1/health" >/dev/null 2>&1; then
    echo ""
    echo "ERROR: API never came up. Check: docker compose -f $COMPOSE_FILE logs api" >&2
    exit 1
fi

echo "→ Configuring music library path to /music…"
curl -fsS -X PUT "$API_BASE/api/v1/settings" \
    -H 'Content-Type: application/json' \
    -d '{"music_library_paths": ["/music"]}' \
    | python3 -m json.tool > /dev/null

echo "→ Creating 'Demo' profile…"
PROFILE_JSON="$(curl -fsS -X POST "$API_BASE/api/v1/profiles" \
    -H 'Content-Type: application/json' \
    -d '{"name": "Demo", "color": "#7c3aed"}')"
PROFILE_ID="$(printf '%s' "$PROFILE_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin)["id"])')"
echo "   profile id: $PROFILE_ID"

echo "→ Triggering library scan…"
# This runs scan+analysis, but newly discovered tracks land in
# PENDING_REVIEW and aren't analyzed until approved.
curl -fsS -X POST "$API_BASE/api/v1/library/sync" \
    -H 'Content-Type: application/json' \
    -d '{}' \
    | python3 -m json.tool > /dev/null

echo "→ Waiting for scan to discover tracks…"
for _ in $(seq 1 30); do
    pending=$(curl -fsS "$API_BASE/api/v1/pending-tracks/stats" \
        -H "X-Profile-ID: $PROFILE_ID" 2>/dev/null \
        | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d.get("total",0))' 2>/dev/null || echo 0)
    if [ "$pending" -gt 0 ]; then
        echo "   $pending tracks awaiting approval."
        break
    fi
    sleep 2
done

echo "→ Auto-approving all pending tracks + queuing analysis…"
curl -fsS -X POST "$API_BASE/api/v1/pending-tracks/bulk/approve-all" \
    -H 'Content-Type: application/json' \
    -H "X-Profile-ID: $PROFILE_ID" \
    -d '{"queue_analysis": true}' \
    | python3 -m json.tool > /dev/null

# Wait for the initial sync to finish before re-triggering (it cannot start
# while a sync is running — returns already_running and skips analysis).
for _ in $(seq 1 30); do
    s=$(curl -fsS "$API_BASE/api/v1/library/sync/status" 2>/dev/null \
        | python3 -c 'import json,sys; print(json.load(sys.stdin).get("status","?"))' 2>/dev/null || echo "?")
    [ "$s" = "completed" ] || [ "$s" = "idle" ] || [ "$s" = "not_running" ] && break
    sleep 3
done

echo "→ Re-triggering sync to run analysis on the newly-active tracks…"
curl -fsS -X POST "$API_BASE/api/v1/library/sync" \
    -H 'Content-Type: application/json' \
    -d '{}' \
    | python3 -m json.tool > /dev/null

echo "→ Polling sync status (analysis can take ~60s per track on CPU)…"
while :; do
    STATUS_JSON="$(curl -fsS "$API_BASE/api/v1/library/sync/status" || echo '{}')"
    STATE="$(printf '%s' "$STATUS_JSON" | python3 -c '
import json, sys
try:
    d = json.load(sys.stdin)
except Exception:
    print("unknown"); sys.exit(0)
p = d.get("progress") or {}
msg = d.get("message") or p.get("message") or ""
done = p.get("analyzed", 0)
total = p.get("total", 0)
print(f"{d.get(\"status\",\"?\")}|{done}|{total}|{msg}")
')"
    IFS='|' read -r S DONE TOTAL MSG <<<"$STATE"
    printf "\r   %-10s %s/%s %s" "$S" "$DONE" "$TOTAL" "$MSG"
    case "$S" in
        idle|completed|error|not_running) echo ""; break ;;
    esac
    sleep 5
done

if [ "$S" = "error" ]; then
    echo "Sync reported an error. Last status:" >&2
    printf '%s' "$STATUS_JSON" | python3 -m json.tool >&2
    exit 1
fi

echo ""
echo "✓ Analysis complete."
echo ""
echo "Next steps:"
echo "  export DEMO_LOCAL_DB='$DEMO_LOCAL_DB'"
echo "  export DEMO_NEON_URL='postgresql://…your-neon-url…'"
echo "  export FLY_APP=familiar-demo"
echo "  ./scripts/seed-demo-library.sh"
echo ""
echo "When you're done seeding, tear down with:"
echo "  ./scripts/analyze-demo-library.sh down"
