#!/usr/bin/env bash
set -euo pipefail

# fetch-demo-library.sh — Download Kevin MacLeod's Creative Commons genre
# samplers from the Internet Archive into ./demo-library/ for the Familiar
# public review server.
#
# Uses a curated list of verified archive.org items (Kevin MacLeod's sampler
# albums, each CC-BY 3.0) rather than searching the noisy IA audio catalog.
# Attempting to filter generic IA results for "music" produces podcasts,
# cult recordings, and religious lectures, which is why we pin the source.
#
# Usage:
#   ./scripts/fetch-demo-library.sh [target_dir] [max_per_sampler]
#
# Defaults: target_dir=./demo-library, max_per_sampler=6 (≈36 total tracks)

TARGET_DIR="${1:-./demo-library}"
MAX_PER_SAMPLER="${2:-6}"

command -v curl >/dev/null    || { echo "curl required" >&2; exit 1; }
command -v python3 >/dev/null || { echo "python3 required" >&2; exit 1; }

mkdir -p "$TARGET_DIR"

# Verified IA items with permissive CC licenses. Format: <slug>|<ia_identifier>
#
# Kevin MacLeod samplers carry an explicit CC-BY 3.0 `licenseurl` in their
# IA metadata. "Calming" and "The Ambient" don't have the field populated
# but are covered by Kevin MacLeod's universal CC-BY 3.0 grant at
# incompetech.com — the artist's standard license covers all his work.
# Jahzzar / Hussalonia / Nicolas Falcon have explicit `licenseurl` fields.
SAMPLERS=(
    "classical|Classical_Sampler-9615"
    "jazz|Jazz_Sampler-9619"
    "blues|Blues_Sampler-9614"
    "funk|Funk_Sampler-9613"
    "global|Global_Sampler-9620"
    "contemporary|Contemporary_Sampler-9616"
    "ambient|Kevin-MacLeod_The-Ambient_2014_FullAlbum"
    "calming|Kevin-MacLeod_Calming_2014_FullAlbum"
    "jahzzar|Grab_Bag-12446"
    "hussalonia|The_Public_Domain_EP"
    "nicolasfalcon|NicolasFalcon-NicolasFalconaaahh011"
)

ATTRIBUTIONS="$TARGET_DIR/ATTRIBUTIONS.md"
cat > "$ATTRIBUTIONS" <<'HDR'
# Demo library attributions

All tracks are Creative Commons (CC-BY, CC-BY-SA) or public domain,
sourced from the Internet Archive. This file is auto-generated by
`scripts/fetch-demo-library.sh`.

Artists:
- Kevin MacLeod (https://incompetech.com) — CC-BY 3.0
- Jahzzar (https://betterwithmusic.com) — CC-BY-SA 3.0
- Hussalonia — CC-BY 4.0
- Nicolas Falcon — CC-BY 3.0

## Source albums

HDR

total_downloaded=0

for entry in "${SAMPLERS[@]}"; do
    SLUG="${entry%%|*}"
    IDENT="${entry##*|}"

    echo "→ $SLUG sampler ($IDENT)"

    META_JSON="$(curl -fsSL --max-time 30 "https://archive.org/metadata/$IDENT" || true)"
    [ -n "$META_JSON" ] || { echo "   (metadata fetch failed, skipping)"; continue; }

    # Extract MP3 filenames (prefer 128Kbps/VBR derivatives).
    FILES_TSV="$(printf '%s' "$META_JSON" | python3 -c '
import json, sys
data = json.load(sys.stdin)
files = data.get("files", [])
picks = []
for f in files:
    name = f.get("name") or ""
    fmt = (f.get("format") or "").lower()
    if not name.lower().endswith(".mp3"): continue
    if "mp3" not in fmt: continue
    title = f.get("title") or name.rsplit(".",1)[0]
    picks.append((name, title))
for n, t in picks:
    print(f"{n}\t{t}")
')"

    echo "- **$(echo "$IDENT" | tr '_' ' ')** — https://archive.org/details/$IDENT" >> "$ATTRIBUTIONS"

    count=0
    while IFS=$'\t' read -r mp3_name track_title; do
        [ "$count" -ge "$MAX_PER_SAMPLER" ] && break
        [ -n "$mp3_name" ] || continue

        title_slug=$(printf '%s' "$track_title" | tr '[:upper:]' '[:lower:]' \
            | tr -c 'a-z0-9' '-' | tr -s '-' | sed 's/^-//;s/-$//' | cut -c1-50)
        [ -n "$title_slug" ] || title_slug="track-$count"

        OUT="$TARGET_DIR/${SLUG}_${title_slug}.mp3"
        if [ -f "$OUT" ]; then
            echo "   ✓ already have: $SLUG / $track_title"
            count=$((count + 1))
            continue
        fi

        # URL-encode each path segment so spaces, apostrophes, etc. in IA
        # filenames (e.g. "Calming/Kevin MacLeod - 01 - Autumn Day.mp3")
        # don't break curl.
        encoded_mp3="$(printf '%s' "$mp3_name" | python3 -c '
import sys
from urllib.parse import quote
print("/".join(quote(seg, safe="") for seg in sys.stdin.read().strip().split("/")))
')"
        DL="https://archive.org/download/${IDENT}/${encoded_mp3}"
        echo "   ↓ $track_title"
        if curl -fsSL --retry 2 --max-time 180 -o "$OUT.part" "$DL" 2>/dev/null; then
            mv "$OUT.part" "$OUT"
            count=$((count + 1))
            total_downloaded=$((total_downloaded + 1))
        else
            rm -f "$OUT.part"
            echo "     (download failed, skipping)" >&2
        fi
    done <<<"$FILES_TSV"
done

echo "" >> "$ATTRIBUTIONS"
echo "" >> "$ATTRIBUTIONS"
{
    echo "## Credit line"
    echo ""
    echo "> Demo music by Kevin MacLeod (incompetech.com), Jahzzar (betterwithmusic.com),"
    echo "> Hussalonia, and Nicolas Falcon — licensed under Creative Commons."
} >> "$ATTRIBUTIONS"

echo ""
total_files=$(find "$TARGET_DIR" -maxdepth 1 -name '*.mp3' | wc -l | tr -d ' ')
echo "✓ $total_downloaded new tracks downloaded; $total_files total in $TARGET_DIR"
echo "✓ Attribution written to $ATTRIBUTIONS"
